language: php

php:
  - 5.6
  - 7.0
  - nightly
  - hhvm

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

install:
  - composer self-update --quiet
  - composer --prefer-source update --no-interaction --no-progress -o

script:
  - ./vendor/bin/phpunit -v --debug --coverage-clover=coverage.clover
